language: go

go:
  - tip
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"
  - "1.8.x"
  - "1.7.x"
  - "1.6.x"
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true